### ISSUE TITLE
Packaging questions

### ISSUE THREAD

**Issue by Kixunil** [honzanoll/btcpayserver-stream#1]
Hi, I'm looking into packaging this as a Debian package in [Cryptoanarchy Debian Repository](https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder). From the first look it seems mostly easy but there are some unresolved questions:

* Is it possible to configure port number or, if not, could you add it (I guess should be easy)?
* Would it be possible to have configurable root path? (e.g. `example.com/donate`, `example.com/stream`...)
* How hard would it be to move Streamlabs token configuration from CLI to GUI? Is it something you'd be willing to do?
* (Optional) would it be possible to configure the application using a configuration **file** (or even better parts directory - in the spirit of [`run-parts`](https://www.systutorials.com/docs/linux/man/8-run-parts/)) instead of environment variables?

Edit, forgot to ask:
* What kind of authentication into the administration interface does this use? Would it be possible to have ThunderHub-style SSO?
* Does this project have a unique icon/logo?

Note that I'm not committing into packaging it right now, just want to research this option.

**Comment by honzanoll** [comment]
Hi Martin, I appreciate your interest. Answers to your questions are below.

- Yes, you can set port number in two ways. The simplest is probably using an argument (in the start script) or in the configuration file.
- It is not possible to configure base path now but can be implemented pretty easily.
- Move Streamlabs configuration to GUI is a little bit tricky. You called it _Streamlabs token_ but this is not accurate enough. The Streamlabs access token (used to post donate alert) is automatically stored in the database after each user connects his Streamlabs account. Thus by a user action in GUI. The configuration which you mean identifies the application registered on Streamlabs platform and is a prerequisite of possible function of the application as a whole. So you can't simply move this configuration to GUI, without extending all use cases about missing this configuration.
- The application uses [appsettings.json](https://github.com/honzanoll/btcpayserver-stream/blob/main/src/BTCPayServer.Stream.Portal/appsettings.json) configuration file, where you can configure everything. Usage of environment variables is just a secondary solution, easy to use with Docker.
- The application uses to authenticate users default cookies based implementation of ASP.NET Core. The same implementation as BtcPayServer uses, in fact. I don't know ThunderHub well, so I can't confirm that for sure, but it would be possible, I suppose.
- No, this project doesn't have a unique logo. I'm a graphic illiterate.
