### ISSUE TITLE
Bug: cannot pair with streamlabs

### ISSUE THREAD

**Issue by gorrdy** [honzanoll/btcpayserver-stream#3]
portal_1  | 2023-06-01 20:58:06.2864|ERROR|BTCPayServer.Stream.HttpClients.StreamlabsClient.StreamlabsHttpClient|Error while getting a response: Unauthorized - {"error":"invalid_client","error_description":"Client authentication failed."}
portal_1  | 2023-06-01 20:58:06.2994|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
portal_1  | 2023-06-01 21:02:00.6867|ERROR|BTCPayServer.Stream.HttpClients.StreamlabsClient.StreamlabsHttpClient|Error while getting a response: Unauthorized - {"error":"invalid_client","error_description":"Client authentication failed."}
portal_1  | 2023-06-01 21:02:00.6935|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

<img width="1440" alt="Snímek obrazovky 2023-06-01 v 23 03 01" src="https://github.com/honzanoll/btcpayserver-stream/assets/80678558/f065c0d2-62e4-4de5-81aa-75798eb20373">
<img width="1440" alt="Snímek obrazovky 2023-06-01 v 23 03 09" src="https://github.com/honzanoll/btcpayserver-stream/assets/80678558/fe524891-3abb-4351-8139-8e49f6da6e52">
<img width="1440" alt="Snímek obrazovky 2023-06-01 v 23 03 21" src="https://github.com/honzanoll/btcpayserver-stream/assets/80678558/7f538688-71e2-45a1-93e8-7c1343ab58dc">
<img width="1440" alt="Snímek obrazovky 2023-06-01 v 23 03 31" src="https://github.com/honzanoll/btcpayserver-stream/assets/80678558/19b116eb-0824-4104-827e-e5d5c44bd9c7">
<img width="1440" alt="Snímek obrazovky 2023-06-01 v 23 03 38" src="https://github.com/honzanoll/btcpayserver-stream/assets/80678558/6db13b6e-1336-4525-ac7a-eef0872779b9">

**Comment by gorrdy** [comment]
The connection and pairing with BTCPayServer works fine though.

**Comment by honzanoll** [comment]
Hey Gorrdy, thanks for your feedback.

The problem was caused by the new version of Streamlabs API v2.0, for which the application was not ready. That's why I just released its new version v1.1.0, which fixes it.
